# Generated by Django 4.1.3 on 2022-11-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(to="role.role"),
        ),
    ]
