# Generated by Django 4.2.2 on 2023-07-02 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_profile_mobile_profile_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
