# Generated by Django 4.2.2 on 2023-07-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_rename_name_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="endpoint",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=255, verbose_name="email address"
            ),
        ),
        migrations.AlterIndexTogether(
            name="user",
            index_together={("endpoint", "email"), ("endpoint", "username")},
        ),
    ]
