# Generated by Django 4.2.8 on 2023-12-19 00:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0003_contract_effective_from_alter_contract_expired_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("schema_name", models.CharField(blank=True, max_length=32, null=True)),
                ("month", models.CharField(blank=True, max_length=2, null=True)),
                ("weekday", models.CharField(blank=True, max_length=1, null=True)),
                ("time", models.CharField(blank=True, max_length=5, null=True)),
                ("sort_key", models.IntegerField(db_index=True, null=True)),
            ],
            options={
                "db_table": "app_job",
                "ordering": ["sort_key"],
                "get_latest_by": "updated_at",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_key", models.IntegerField(db_index=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tenant.job",
                    ),
                ),
            ],
            options={
                "db_table": "app_task",
                "ordering": ["sort_key"],
                "get_latest_by": "updated_at",
            },
        ),
    ]
